### ISSUE TITLE
Make it easy to rotate secrets

### ISSUE THREAD

**Issue by foca** [thadeu/branca-ruby#1]
Right now, because the secret is set on the singleton `Branca` object, it's hard to rotate secrets on a live system without downtime. Particularly when the secret is shared between two different servers that need to coordinate the rotation.

Would you be open to a PR that allows us to instantiate `Branca` so that an app can keep more than one instance of it to allow a fallback token?

Something like

``` ruby
configs = [
  Branca.new(ENV.fetch('BRANCA_TOKEN')),
  Branca.new(ENV.fetch('BRANCA_FALLBACK_TOKEN'))
]

configs.each do |b|
  b.decode(token)
rescue RbNaCl::CryptoError
  b == configs.last ? raise : next
end
```

We can keep a default "instance" linked to the singleton, and delegate the current API to that instance, so that the public API works seamlessly.

**Comment by thadeu** [comment]
Hi @foca, first, thank you for the issue. I'm so glad for this.

Sure, free feel to open PR about this.

**Comment by thadeu** [comment]
Hey @foca some advance on your ideia? Free feel talk me about this.

**Comment by thadeu** [comment]
@foca This PR covered your suggestion, ok? #2
